[package]
name = "spin-test-sdk-macro"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
heck = "0.5"
proc-macro2 = "1.0"
quote = "1.0"
syn = { version = "2.0", features = ["full"] }
wit-component = { workspace = true }
wit-parser = { workspace = true }
