[package]
name = "host"
version = "0.1.0"
edition = "2021"

[dependencies]
http = "1.0"
http-body-util = "0.1.1"
hyper = "1.0"
tokio = { version = "1.0", features = ["rt", "macros"] }
spin-test-sdk = { path = "../../crates/rust-sdk" }
