spin_manifest_version = 2

[application]
name = "example"
version = "0.1.0"
authors = ["Ryan Levick <ryan.levick@fermyon.com>"]
description = ""

[[trigger.http]]
route = "/..."
component = "example"

[component.example]
source = "target/wasm32-wasi/release/example.wasm"
allowed_outbound_hosts = []
[component.example.build]
command = "cargo build --target wasm32-wasi --release"
watch = ["src/**/*.rs", "Cargo.toml"]
